name: dps
num_steps: 1000
eps: 1e-04
penalty: 0.1 # not used in our case
pct_chain_elapsed: 0
num_img_log: 10
log_freq: 10
batch_size: 1
add_corrector: False
guidance_strength: 0.3
use_osem_nll: False